### ISSUE TITLE
Docker Build Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#2]
The docker build command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the build command would be formatted as shown below:

```
- docker:
       description:
       build:
            tag:
            file: OPTIONAL
            path: # defaults to "." OPTIONAL
            flags:
                rm: ""
                target: base
```
