### ISSUE TITLE
Docker Run Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#3]
The docker run command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the run command would be formatted as shown below:

```
- docker:
       description:
       run:
            image:
            name: 
            detach: # defaults to false
            ports:
                - host: 
                   container:
            env:
                 password:
            privileged: # defaults to false
            rm: # defaults to false
```
