### ISSUE TITLE
Docker Pull Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#4]
The docker pull command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the pull command would be formatted as shown below:

```
- docker:
       description:
       pull:
            name: 
            tag: 
            digest:
```
