### ISSUE TITLE
Docker Push Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#5]
The docker push command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the push command would be formatted as shown below:

```
- docker:
       description:
       push:
            name: 
            tag: 
```
