### ISSUE TITLE
Docker Login Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#6]
The docker login command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the login command would be formatted as shown below:

```
- docker:
       login:
            username:
            password:
```

**Comment by carolynvs** [comment]
There are some neat things that I think we can plan for to take advantage of what bundles do. For example, the docker username and password will be passed into the bundle as credentials or parameters, and will be available to us as environment variables.

```yaml
credentials:
- name: docker-user
  env: DOCKER_USERNAME
- name: docker-password
  env: DOCKER_PASSWORD

install:
  docker: login
```

The mixin can default the `username` and `password` fields to the environment variables `DOCKER_USERNAME` and `DOCKER_PASSWORD` so that people don't need to fill them in unless they are doing something different than the default.
