### ISSUE TITLE
Docker Remove Command

### ISSUE THREAD

**Issue by gaurimadhok** [deislabs/porter-docker#7]
The docker remove command will be part of the docker mixin to make it easier to use docker from inside a bundle.

The yaml for the remove command would be formatted as shown below:
```
   - docker:
       description:
       remove:
            container:
            force: # defaults to false
```
